# Generated by Django 2.2 on 2021-12-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saliencyimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='saliencyimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
