# Generated by Django 2.2 on 2021-12-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211206_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='saliencyimage',
            name='contour1_x',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='saliencyimage',
            name='contour1_y',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='saliencyimage',
            name='contour2_x',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='saliencyimage',
            name='contour2_y',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='saliencyimage',
            name='contour3_x',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='saliencyimage',
            name='contour3_y',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='saliencyimage',
            name='contour4_x',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='saliencyimage',
            name='contour4_y',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='saliencyimage',
            name='mainComponent_x',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='saliencyimage',
            name='mainComponent_y',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='saliencyimage',
            name='topFeature_x',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='saliencyimage',
            name='topFeature_y',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
